### ISSUE TITLE
CLEAN Database of LIVE before publishing.

### ISSUE THREAD

**Issue by doomsayer2** [fhstp-mfg/mobilot#157]
**FINAL FINAL RELEASE before: 18.12.2016**

Clean the live database of usless mobiduls. @miclaus @kblumenstein @GrischaSchmiedl Please view my suggestions or review them before i or we delete them.

_**To be removed (Mobidulnames - comments):**_
- [x] Waldpädagogik im Gespräch (has nothing special and only seems to be a test)
- [x] Student Guide (seems nice but usless and not fully working)
- [x] Sportunion (is empty)
- [x] Sports around FH St.Pölten (same as Sportunion)
- [x] Kerstin (just a test mobidul)
- [x] Wald und Wiese (just a test mobidul again)
- [x] Wald und Wiese II (also just a test)
- [x] Urlaub (test mobidul as it seems)
- [x] Smarte Rally (nothing filled in and seems as tets)
- [x] Severin (also just a test)
- [x] Wien ist Toll (seems nice but never finished)
- [x] HLW neu entdeckt (just one station)
- [x] TestModul (as name says)
- [x] Herbst (not working in any way)
- [x] Gratis WLAN Wien (also unfinished and not working)
- [x] MeinLaptopIstBlöd (what to say here.....)
- [x] Feine Clubs in Wien! (also one station only and not finished)
- [x] Kremser Brücke (seems to be a test and contains images)
- [x] Brücke über die Bundesstraße (does nothing)
- [x] lindaceleb (does also nothing)
- [x] ItWorks (also just a test)
- [x] Tschaupi (seems to be also a test)
- [x] Fitnesstreffen im Traisenpark (also no stations or content)
- [ ] Norbert (2) (as duplication of Norbert (1))
- [x] Tutorial Mobidul (usless)
- [x] MyMobidul (also unused)

_**To be fixed (Mobidulnames):**_
- [ ] Stadt Pressbaum (huge mobidul but no station working)
- [ ] Denkwerstatt (all images not working but great mobidul)
- [x] Ternberg (also images not working)
- [x] Torpergrunde Herbst (not working sadly though huge)
- [ ] HAK St.Pölten Workshop (content also not loading)
- [ ] Workshop 20. Jänner (content needs to be fixed)
- [x] Tullnerbach Rätselrally (maybe will be finished)

**

> NOTE:
> FINISHED!!!! 16.12.2016 17:36

**

**Comment by kblumenstein** [comment]
(from remove section) NO delete for:
Norbert (2) -> is not really a duplicate, it is Norbert (1) the other way around

(from fixed section) delete for:
Tullnerbach Rätselrally - can be deleted, was only a pre-stage for Norbert (1 & 2)

**Comment by GrischaSchmiedl** [comment]
**From "to be removed":** 
I suggest to:
rename "Norbert (1)" to "Norbert Tour"
rename "Norbert (2)" to "Norbert Retour"
(and it's not only the other way round but rather a slightly different story) - BTW the station-prints are still in place on all but one station.

all other mobiduls in this category can be deleted.

**In "to be fixed":**
Stadt Pressbaum: the original data com from an older version of mobilot that is eventually still available as a subdomain of hlwpressabum.at (but I don't know the exact URL). If it can be restored for the current version, this would be the best content we ever had.

_Denkwerkstatt_: was used for a scavenger hunt game: eventually interesting to demonstrate the concept if working, otherwise delete. 
BTW there was an even better scavenger game rally we organised in autumn with kids from Sportunion Tullnerbach, also in the region of the Norbertinum school in Tullnerbach. It has the name "_Sportunion_" and is listed in the "to be removed" section. I don't know why it's empty - there should be about 7-10 stations. If one of these two mobilduls can be saved, we should definitely save it


 Ternberg (also images not working): DELETE (just photos of a Sportunion summer camp tour)
 Tropbergrunde Herbst: DELETE (just a personal tour with my kids for testing reasons)
 HAK St.Pölten Workshop (content also not loading): DON'T KNOW
 Workshop 20. Jänner (content needs to be fixed): DON'T KNOW
 Tullnerbach Rätselrally (maybe will be finished): DELETE

**Comment by doomsayer2** [comment]
Cleaned.
