### ISSUE TITLE
Drag and Drop on mobile devices

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#30]
- [x] Change Station order
- [x] Change Menu order
- [x] Change Category order

_Delayed (as not totally necessary)_
- [x] Change Station Element order

**Comment by josephmiclaus** [comment]
React is now implemented on branch `init-react` since 1ebfa44.

The main React file is unter `public/app/app.react.js` and compiles and bundles everything required to `public/assets/js/react.bundle.js`.

We write React in ES6 (stage-2) and JSX code, which have to be compiled running:

``` bash
npm run watchify
```

**TIPP**: Create an alias for your terminal.

``` bash
alias nrw="npm run watchify"
```

**Comment by josephmiclaus** [comment]
Okay, so I tried a few things and we should postpone React usage until we have a good way to structure components and use JSX. Without JSX I don't see a chance using it productively!

Therefore I'm moving this to `v1.1`

**Comment by josephmiclaus** [comment]
Posponed, see d1cecfa for current code examples.

**Comment by doomsayer2** [comment]
Fixed all and visual enhancements. Also working for menu, categories and stations, but for editor only on non mobile devices. All other works mobile and desktop.

**Comment by doomsayer2** [comment]
Works now too for elements in editor.
